global:
  username: xxxxxxx
  password: ********
  since : "01.01.2021" # date in format dd.mm.yyyy
git:
  - url: https://github.com/xxxx/release_metrics_generator.git
  - url: https://github.com/xxxx/fileuploader.git
  - url: https://github.com/xxxx/fileviewer.git

